vendor: Netcracker Technology
name: KubeMarine
version: v0.8.0
website_url: https://github.com/Netcracker/KubeMarine
documentation_url: https://github.com/Netcracker/KubeMarine/tree/main/documentation
product_logo_url: https://avatars.githubusercontent.com/u/84337028?s=200&v=4
type: distribution
description: 'Management tool for Kubernetes cluster deployment and maintenance'
